/*
  QUIZ DAS COPAS — Pedro Luiz
  Para ranking global, configure SUPABASE_URL e SUPABASE_ANON_KEY.
  Nunca coloque a service_role key neste arquivo.
*/
const SUPABASE_URL = '';
const SUPABASE_ANON_KEY = '';
const RANKING_TABLE = 'ranking';
let player='',questions=[],pos=0,total=0,attempt=0,locked=false;
const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function safe(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function startGame(){player=$('name').value.trim().slice(0,24);if(!player){$('name').focus();$('name').animate([{transform:'translateX(-4px)'},{transform:'translateX(4px)'},{transform:'none'}],250);return}const levels=['Fácil','Médio','Difícil','Muito difícil'];questions=[];levels.forEach(l=>questions.push(...shuffle(BANK.filter(x=>x.level===l)).slice(0,5)));questions=shuffle(questions);pos=0;total=0;show('game');render()}
function render(){attempt=0;locked=false;const q=questions[pos];$('qcount').textContent=`Pergunta ${pos+1}/20`;$('level').textContent=q.level;$('score').textContent=total;$('progress').style.width=`${(pos+1)*5}%`;$('question').textContent=q.q;$('attempts').textContent='Primeira tentativa • vale 4 pontos';$('feedback').classList.add('hidden');$('info').classList.add('hidden');$('next').classList.add('hidden');$('next').textContent=pos===19?'VER RESULTADO →':'PRÓXIMA PERGUNTA →';$('options').innerHTML=q.a.map((a,i)=>`<button class="option" data-i="${i}">${String.fromCharCode(65+i)}) ${safe(a)}</button>`).join('');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>answer(+b.dataset.i,b))}
function answer(i,btn){if(locked)return;const q=questions[pos];attempt++;if(i===q.c){const pts=5-attempt;total+=pts;locked=true;btn.style.borderColor='var(--green)';btn.style.background='#123a25';$('score').textContent=total;$('feedback').textContent=`✓ Acertou! +${pts} ponto${pts>1?'s':''}.`;$('feedback').classList.remove('hidden');showInfo(q);document.querySelectorAll('.option').forEach(b=>b.disabled=true);$('next').classList.remove('hidden')}else{btn.classList.add('wrong');btn.disabled=true;if(attempt<4){const pts=4-attempt;$('attempts').textContent=`Tentativa ${attempt+1} de 4 • se acertar agora vale ${pts} ponto${pts>1?'s':''}`;$('feedback').textContent='Você errou esta tentativa. A resposta correta continua escondida!';$('feedback').classList.remove('hidden')}else{locked=true;document.querySelectorAll('.option').forEach(b=>b.disabled=true);$('attempts').textContent='4 tentativas utilizadas';$('feedback').textContent='Você não acertou. A resposta correta continua escondida até o final.';$('feedback').classList.remove('hidden');$('next').classList.remove('hidden')}}}
function showInfo(q){if(q.type==='scorer'||q.type==='team'){const title=q.type==='scorer'?'👤 Sobre o jogador':'🌎 Sobre a seleção';$('info').innerHTML=`<b>${title}</b><br>${safe(q.bio)}`;$('info').classList.remove('hidden')}}
function next(){if(pos<19){pos++;render()}else finish()}
async function finish(){show('result');$('hello').textContent=`Parabéns, ${player}!`;$('finalScore').textContent=`${total} / 80`;const lvl=total>=65?'Muito difícil':total>=45?'Difícil':total>=25?'Médio':'Fácil';$('finalLevel').innerHTML=`Nível de desempenho: <span class="pill">${lvl}</span>`;await saveScore();await renderRanking()}
function localGet(){return JSON.parse(localStorage.getItem('copasRanking')||'[]')}
function localSave(){const r=localGet();r.push({name:player,score:total,date:new Date().toLocaleDateString('pt-BR')});r.sort((a,b)=>b.score-a.score);localStorage.setItem('copasRanking',JSON.stringify(r.slice(0,100)))}
async function saveScore(){localSave();if(!SUPABASE_URL||!SUPABASE_ANON_KEY)return;try{await fetch(`${SUPABASE_URL}/rest/v1/${RANKING_TABLE}`,{method:'POST',headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,'Content-Type':'application/json','Prefer':'return=minimal'},body:JSON.stringify({name:player,score:total})})}catch(e){console.warn('Ranking online indisponível',e)}}
async function renderRanking(){let r=localGet(),online=false;if(SUPABASE_URL&&SUPABASE_ANON_KEY){try{const res=await fetch(`${SUPABASE_URL}/rest/v1/${RANKING_TABLE}?select=name,score,created_at&order=score.desc,created_at.asc&limit=100`,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`}});if(res.ok){r=await res.json();online=true}}catch(e){}}r=r.map((x,i)=>({name:x.name,score:x.score,date:x.created_at?new Date(x.created_at).toLocaleDateString('pt-BR'):x.date||''}));let html=`<h3>🏅 Ranking ${online?'GLOBAL':'LOCAL'}</h3><table><tr><th>#</th><th>Jogador</th><th>Pontos</th><th>Data</th></tr>`;r.slice(0,100).forEach((p,i)=>{const me=p.name===player&&Number(p.score)===total;html+=`<tr class="${me?'me':''}"><td>${i+1}</td><td>${safe(p.name)}</td><td>${p.score}</td><td>${safe(p.date)}</td></tr>`});html+='</table>';if(!r.length)html+='<p class="hint">Ainda não há jogadores no ranking.</p>'; $('rankBox').innerHTML=html}
$('start').onclick=startGame;$('name').addEventListener('keydown',e=>{if(e.key==='Enter')startGame()});$('next').onclick=next;$('again').onclick=()=>{$('name').value=player;show('home')};$('clear').onclick=()=>{if(confirm('Apagar o ranking salvo neste navegador?')){localStorage.removeItem('copasRanking');renderRanking()}};
